## Custom MSF-OCB configuration file "docker-compose.yml" for PHP app "OSTicket" for <https://helpdesk.sherlog.ocb.msf.org/> (<https://osticket.com/> with addition of <https://osticketawesome.com> plus customisations)
## XKa - v2021.06.22.0 - Base configuration file, to be complemented with specific configuration override files (dev, staging, prod...)

version: '3.7'

services:

  db:
    container_name: sherlog-osticket-db
    restart: unless-stopped
    env_file: .env
    image: mysql:5
    volumes:
      - type: volume
        source: sherlog-osticket-db-data
        target: /var/lib/mysql

  web:
    container_name: sherlog-osticket-web
    restart: unless-stopped
    env_file: .env
    environment:
      - "MYSQL_HOST=${MYSQL_HOST:-db}"
    image: docker.pkg.github.com/msf-ocb/sherlog-osticket-docker/sherlog-osticket-web:deploy
    volumes:
      - type: bind
        source: ./sherlog-osticket-web-html
        target: /var/www/html
    tmpfs:
      - /tmp
      - /run
    expose:
      - "${HTTPD_PORT}"
    networks:
      - web
      - default
    depends_on:
      - db

volumes:
    sherlog-osticket-db-data:

networks:
  web:
    external: true

##EOF
