## Custom MSF-OCB configuration file "docker-compose.yml" for PHP app "OSTicket" for <https://helpdesk.sherlog.ocb.msf.org/> (<https://osticket.com/> with addition of <https://osticketawesome.com> plus customisations)
## XKa - v2021.06.09.0 - Variant: Development

version: '3.5'
services:

  db:
    container_name: sherlog-osticket-db
#    restart: always
    env_file: .env
    image: mysql:5
    volumes:
      - type: volume
        source: sherlog-osticket-db-data
        target: /var/lib/mysql

  web:
    container_name: sherlog-osticket-web
#    restart: always
    env_file: .env
    environment:
      - "MYSQL_HOST=${MYSQL_HOST:-db}"
    image: docker.pkg.github.com/msf-ocb/sherlog-osticket-docker/sherlog-osticket-web:deploy
#    image: msfocb/osticket_awesome
#    build:
#      context: docker-sherlog-osticket-web
#      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./sherlog-osticket-web-html
        target: /var/www/html
    tmpfs:
      - /tmp
      - /run
    expose:
      - "${HTTPD_PORT}"
### DEBUG >>> ###
#    ports:
#      - "${HTTPD_PORT}:${HTTPD_PORT}"
### DEBUG <<< ###
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.osticket.rule=Host(`helpdesk.sherlog.ocb.msf.org`)"
#      - "traefik.http.routers.osticket.entrypoints=websecure"
    networks:
      - web
      - default
    depends_on:
      - db

#  backup:
#    container_name: sherlog-osticket-backup
#    image: msfocbehealth/backup:latest
#    labels:
#      - "org.msf.description=backup"
#    restart: always
#    env_file: .env
#    volumes:
#      - type: volume
#        source: sherlog-osticket-backup-data
#        target: /backups
#    depends_on:
#      - db

volumes:
    sherlog-osticket-db-data:
#    sherlog-osticket-backup-data:

networks:
  web:
    external: true

##EOF
