# (Reference: <https://github.com/docker/build-push-action/tree/releases/v1>)

name: Publish Docker image

on:
  push:
    branches:
     - deploy
    
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Push relay to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: ./docker-sherlog-osticket-web
          registry: docker.pkg.github.com
          repository: msf-ocb/sherlog-osticket/sherlog-osticket-web
          tag_with_ref: true
